name: inventory_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
